# Generated by Django 2.0.3 on 2018-05-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='captain',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AddField(
            model_name='flight',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Captain'),
        ),
    ]
